---
- hosts: dockerhost
  tasks:

  - name: stop exiting container
    command: docker stop regapp-server
    ignore_errors: yes                 

  - name: remove stopped container
    command: docker rm regapp-server
    ignore_errors: yes

  - name: remove docker image
    command: docker rmi kashi779/regapp:latest
    ignore_errors: yes            

  - name: create new container from image
    command: docker  run -d --name regapp-server -p 8082:8080 kashi779/regapp:latest 
